import type { Game } from "@/types";

export const GAMES: Game[] = [
  {
    id: "wordrush",
    slug: "wordrush",
    title: "WordRush",
    description: "Guess the hidden word before time runs out. A new word every day.",
    category: "word",
    emoji: "🔤",
    color: "bg-purple-50",
    accent: "text-purple-600",
    is_pro_only: false,
    is_daily: true,
    min_session_seconds: 60,
    max_session_seconds: 300,
    tags: ["daily", "popular", "word"],
  },
  {
    id: "tapblitz",
    slug: "tapblitz",
    title: "TapBlitz",
    description: "Tap the targets as fast as you can. How high can you score in 30 seconds?",
    category: "reflex",
    emoji: "⚡",
    color: "bg-amber-50",
    accent: "text-amber-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 30,
    max_session_seconds: 60,
    tags: ["reflex", "fast", "viral"],
  },
  {
    id: "slidegrid",
    slug: "slidegrid",
    title: "SlideGrid",
    description: "Slide the tiles into the correct order. Simple rules, endless challenge.",
    category: "puzzle",
    emoji: "🧩",
    color: "bg-teal-50",
    accent: "text-teal-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 60,
    max_session_seconds: 600,
    tags: ["puzzle", "classic"],
  },
  {
    id: "quizdrop",
    slug: "quizdrop",
    title: "QuizDrop",
    description: "Rapid-fire trivia across 10 categories. Beat your streak.",
    category: "trivia",
    emoji: "❓",
    color: "bg-blue-50",
    accent: "text-blue-600",
    is_pro_only: false,
    is_daily: true,
    min_session_seconds: 60,
    max_session_seconds: 180,
    tags: ["trivia", "daily", "knowledge"],
  },
  {
    id: "colorsnap",
    slug: "colorsnap",
    title: "ColorSnap",
    description: "Match the exact colour shade. Train your eye, beat your friends.",
    category: "visual",
    emoji: "🎨",
    color: "bg-pink-50",
    accent: "text-pink-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 30,
    max_session_seconds: 120,
    tags: ["visual", "shareable", "unique"],
  },
  {
    id: "numchain",
    slug: "numchain",
    title: "NumChain",
    description: "Connect numbers on the grid to reach the target sum.",
    category: "math",
    emoji: "🔢",
    color: "bg-green-50",
    accent: "text-green-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 60,
    max_session_seconds: 300,
    tags: ["math", "puzzle", "brain"],
  },
  {
    id: "dodgedash",
    slug: "dodgedash",
    title: "DodgeDash",
    description: "Dodge the obstacles as long as you can. Mobile-first, endlessly addictive.",
    category: "arcade",
    emoji: "🌪️",
    color: "bg-orange-50",
    accent: "text-orange-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 15,
    max_session_seconds: 180,
    tags: ["arcade", "mobile", "addictive"],
  },
  {
    id: "memoryflip",
    slug: "memoryflip",
    title: "MemoryFlip",
    description: "Flip and match the cards. All ages, emoji themes, timed rounds.",
    category: "memory",
    emoji: "🃏",
    color: "bg-violet-50",
    accent: "text-violet-600",
    is_pro_only: false,
    is_daily: false,
    min_session_seconds: 30,
    max_session_seconds: 300,
    tags: ["memory", "family", "classic"],
  },
];

export function getGameBySlug(slug: string): Game | undefined {
  return GAMES.find((g) => g.slug === slug);
}

export function getDailyGames(): Game[] {
  return GAMES.filter((g) => g.is_daily);
}

export function getFreeGames(): Game[] {
  return GAMES.filter((g) => !g.is_pro_only);
}
